import { useEffect, useRef, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { PageSkeleton, PageState } from '../../components/PageState'
import { businessDateTimeLocalValue } from '../../lib/dateTime'
import { useAuth } from '../auth/auth-context'
import { useMaintenanceFormOptions } from '../maintenances/maintenanceQueries'
import { approveInternalMaintenanceRequest, convertInternalMaintenanceRequest, rejectInternalMaintenanceRequest } from './maintenanceRequestApi'
import { requestKeys, useInternalRequestDetails, useInternalRequestList } from './maintenanceRequestQueries'
import type { RequestConversionInput, RequestCriticality, RequestFilters, TechnicalPriority } from './types'
import { criticalityLabel, requestStatusLabel, technicalPriorityLabel } from './maintenanceRequestValidation'
import { useQueryClient } from '@tanstack/react-query'

function dateTime(value: string) { return new Intl.DateTimeFormat('pt-BR',{dateStyle:'medium',timeStyle:'short',timeZone:'America/Sao_Paulo'}).format(new Date(value)) }
function Badge({value,type}:{value:string;type:'status'|'criticality'|'priority'}) { return <span className={`request-badge request-badge--${value}`}>{type==='status'?requestStatusLabel(value):type==='priority'?`Prioridade ${technicalPriorityLabel(value as RequestCriticality)}`:criticalityLabel(value as RequestCriticality)}</span> }

export function InternalMaintenanceRequestListPage() {
  const [search,setSearch]=useState(''); const [filters,setFilters]=useState<RequestFilters>({status:'',criticality:''}); const [page,setPage]=useState(1)
  const {organization,query,deferred}=useInternalRequestList(search,filters,page); const loading=organization.isLoading||query.isLoading; const error=organization.error??query.error
  return <section className="clients-page internal-request-page" aria-labelledby="internal-requests-title"><div className="module-heading"><div><span className="eyebrow">Portal da Academia</span><h1 id="internal-requests-title">Solicitações</h1><p>Analise os relatos recebidos. A prioridade técnica é independente da criticidade percebida pela academia.</p></div></div>
    <div className="internal-request-toolbar"><label><span className="sr-only">Pesquisar solicitações</span><input type="search" value={search} onChange={(e)=>{setSearch(e.target.value);setPage(1)}} placeholder="Título, cliente ou equipamento"/></label><select aria-label="Filtrar por status" value={filters.status} onChange={(e)=>{setFilters({...filters,status:e.target.value});setPage(1)}}><option value="">Todos os status</option><option value="pending">Pendente</option><option value="approved">Aprovada</option><option value="rejected">Rejeitada</option><option value="converted">Convertida</option><option value="cancelled">Cancelada</option></select><select aria-label="Filtrar por criticidade" value={filters.criticality} onChange={(e)=>{setFilters({...filters,criticality:e.target.value});setPage(1)}}><option value="">Todas as criticidades</option><option value="low">Baixa</option><option value="medium">Média</option><option value="high">Alta</option><option value="critical">Crítica</option></select></div>
    {loading&&<PageSkeleton rows={5}/>} {!loading&&error&&<PageState tone="error" title="Não foi possível carregar as solicitações" description={error instanceof Error?error.message:'Tente novamente.'} actionLabel="Tentar novamente" onAction={()=>void query.refetch()}/>} {!loading&&!error&&query.data?.items.length===0&&<PageState title={deferred||filters.status||filters.criticality?'Nenhuma solicitação encontrada':'Nenhuma solicitação recebida'} description={deferred||filters.status||filters.criticality?'Revise a busca e os filtros.':'As solicitações enviadas pelo Portal aparecerão aqui.'}/>} {Boolean(query.data?.items.length)&&<div className="internal-request-list"><div className="internal-request-list__head"><span>Solicitação</span><span>Academia / unidade</span><span>Estado</span><span>Recebida</span></div>{query.data?.items.map((item)=><Link to={`/app/solicitacoes/${item.id}`} key={item.id}><div><strong>{item.title}</strong><span>{item.equipment_name}</span></div><div><strong>{item.client_name}</strong><span>{item.location_name}</span></div><div className="request-card__meta"><Badge value={item.status} type="status"/>{item.technical_priority?<Badge value={item.technical_priority} type="priority"/>:<Badge value={item.reported_criticality} type="criticality"/>}</div><time dateTime={item.created_at}>{dateTime(item.created_at)}</time></Link>)}</div>}
    {query.data&&query.data.pageCount>1&&<nav className="portal-pagination" aria-label="Paginação"><button disabled={page===1} onClick={()=>setPage(page-1)}>← Anterior</button><span>Página <strong>{page}</strong> de {query.data.pageCount}</span><button disabled={page>=query.data.pageCount} onClick={()=>setPage(page+1)}>Próxima →</button></nav>}
  </section>
}

type DecisionMode = 'approve'|'reject'|'convert'|null

export function InternalMaintenanceRequestDetailsPage() {
  const {requestId}=useParams(); const navigate=useNavigate(); const {accessContext}=useAuth(); const queryClient=useQueryClient()
  const {organization,query}=useInternalRequestDetails(requestId); const options=useMaintenanceFormOptions(); const loading=organization.isLoading||query.isLoading; const error=organization.error??query.error
  const [mode,setMode]=useState<DecisionMode>(null); const [priority,setPriority]=useState<TechnicalPriority>('medium'); const [publicResponse,setPublicResponse]=useState(''); const [internalNote,setInternalNote]=useState('')
  const [conversion,setConversion]=useState<RequestConversionInput>({maintenanceType:'corrective',scheduledAt:businessDateTimeLocalValue(new Date()),responsibleTechnicianId:''})
  const [busy,setBusy]=useState(false); const [actionError,setActionError]=useState(''); const [success,setSuccess]=useState('')
  const decisionDialogRef=useRef<HTMLDivElement>(null); const decisionTriggerRef=useRef<HTMLButtonElement>(null)
  useEffect(()=>{if(!mode)return; const dialog=decisionDialogRef.current; const focusable=()=>Array.from(dialog?.querySelectorAll<HTMLElement>('button:not([disabled]), input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [href], [tabindex]:not([tabindex="-1"])')??[]); focusable()[0]?.focus(); const onKey=(event:KeyboardEvent)=>{if(event.key==='Escape'&&!busy){closeDecision();return} if(event.key!=='Tab')return; const controls=focusable(); const first=controls[0]; const last=controls.at(-1); if(!first||!last)return; if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}; document.addEventListener('keydown',onKey); return()=>document.removeEventListener('keydown',onKey)},[mode,busy])
  if(loading)return <PageSkeleton rows={6}/>
  if(error||!query.data?.request)return <PageState tone="error" title="Solicitação indisponível" description={error instanceof Error?error.message:'Não encontrada neste tenant.'} actionLabel="Voltar" onAction={()=>navigate('/app/solicitacoes')}/>
  const item=query.data.request; const isOwner=accessContext?.kind==='internal_owner'
  function openDecision(next:Exclude<DecisionMode,null>,trigger:HTMLButtonElement){decisionTriggerRef.current=trigger;setActionError('');setMode(next)}
  function closeDecision(){setMode(null);requestAnimationFrame(()=>decisionTriggerRef.current?.focus())}
  async function refresh(message:string){await Promise.all([query.refetch(),queryClient.invalidateQueries({queryKey:requestKeys.internal()})]);setSuccess(message);closeDecision()}
  async function act(action:'approve'|'reject'|'convert') { if(!organization.data||!requestId||busy)return; setActionError('')
    if(action==='reject'&&publicResponse.trim().length<3){setActionError('Informe uma resposta pública clara com pelo menos 3 caracteres.');return}
    if(action==='convert'&&(!conversion.scheduledAt||!conversion.responsibleTechnicianId)){setActionError('Informe a data do atendimento e o técnico responsável.');return}
    setBusy(true); try {
      if(action==='approve'){await approveInternalMaintenanceRequest(organization.data,requestId,{priority,publicResponse,internalNote});await refresh('Solicitação aprovada. Nenhuma OS foi criada.')}
      if(action==='reject'){await rejectInternalMaintenanceRequest(organization.data,requestId,{publicResponse,internalNote});await refresh('Solicitação rejeitada e resposta disponibilizada no Portal.')}
      if(action==='convert'){const result=await convertInternalMaintenanceRequest(organization.data,requestId,conversion);await refresh(`Solicitação convertida na ${result.work_order_number}.`)}
    } catch(e){setActionError(e instanceof Error?e.message:'Não foi possível concluir a ação.')} finally{setBusy(false)}
  }
  return <section className="clients-page internal-request-detail"><Link className="back-link" to="/app/solicitacoes">← Voltar para solicitações</Link>
    {success&&<div className="alert alert--success" role="status">{success}</div>}{actionError&&<div className="alert alert--error" role="alert">{actionError}</div>}
    <header className="detail-hero"><div><span className="eyebrow">Solicitação externa</span><h1>{item.title}</h1><p>{item.client_name} · {item.location_name}</p></div><div className="request-card__meta"><Badge value={item.status} type="status"/><Badge value={item.reported_criticality} type="criticality"/>{item.technical_priority&&<Badge value={item.technical_priority} type="priority"/>}</div></header>
    <div className="internal-request-detail__grid"><section><span className="eyebrow">Problema relatado</span><p>{item.description}</p></section><aside><dl><div><dt>Equipamento</dt><dd>{item.equipment_name}</dd></div><div><dt>Categoria</dt><dd>{item.equipment_category}</dd></div><div><dt>Solicitante</dt><dd>{item.requester_name}<small>{item.requester_email}</small></dd></div><div><dt>Recebida em</dt><dd>{dateTime(item.created_at)}</dd></div></dl></aside></div>
    {item.decided_at&&<section className="request-decision-summary"><div><span className="eyebrow">Decisão técnica</span><h2>{requestStatusLabel(item.status)}</h2></div><dl><div><dt>Prioridade técnica</dt><dd>{technicalPriorityLabel(item.technical_priority)}</dd></div><div><dt>Decidida em</dt><dd>{dateTime(item.decided_at)}</dd></div><div><dt>Responsável</dt><dd>{item.decided_by_name||'Owner da organização'}</dd></div></dl>{item.public_response&&<div><strong>Resposta para a academia</strong><p>{item.public_response}</p></div>}{item.internal_decision_note&&<div className="request-internal-note"><strong>Nota interna</strong><p>{item.internal_decision_note}</p></div>}</section>}
    {item.status==='pending'&&isOwner&&<section className="request-decision-panel"><div><span className="eyebrow">Análise do owner</span><h2>Decidir solicitação</h2><p>Aprovar não cria uma ordem de serviço. A conversão será uma etapa separada.</p></div><div className="request-decision-actions"><button className="primary-button primary-button--compact" onClick={event=>openDecision('approve',event.currentTarget)}>Aprovar</button><button className="secondary-button" onClick={event=>openDecision('reject',event.currentTarget)}>Rejeitar</button></div></section>}
    {item.status==='approved'&&isOwner&&<section className="request-decision-panel"><div><span className="eyebrow">Próxima etapa</span><h2>Converter em ordem de serviço</h2><p>A OS será criada como rascunho. Diagnóstico, serviço, valores e peças continuarão vazios.</p></div><button className="primary-button primary-button--compact" onClick={event=>openDecision('convert',event.currentTarget)}>Preparar conversão</button></section>}
    {!isOwner&&item.status!=='converted'&&<div className="request-readonly-note"><strong>Acesso técnico</strong><span>Você pode consultar a análise, mas somente um owner pode decidir ou converter.</span></div>}
    {item.status==='converted'&&item.maintenance_id&&<section className="request-converted-link"><div><span className="eyebrow">Ordem de serviço vinculada</span><h2>{item.work_order_number}</h2><p>O relato original permanece separado do diagnóstico técnico.</p></div><Link className="primary-button primary-button--compact" to={`/app/manutencoes/${item.maintenance_id}`}>Abrir OS</Link></section>}
    {mode&&<section className="request-decision-dialog" role="dialog" aria-modal="true" aria-labelledby="request-decision-title"><div ref={decisionDialogRef}><span className="eyebrow">Confirmação controlada</span><h2 id="request-decision-title">{mode==='approve'?'Aprovar solicitação':mode==='reject'?'Rejeitar solicitação':'Converter em OS'}</h2>
      {mode==='approve'&&<div className="request-decision-fields"><label><span>Prioridade técnica *</span><select value={priority} onChange={e=>setPriority(e.target.value as TechnicalPriority)}><option value="low">Baixa</option><option value="medium">Média</option><option value="high">Alta</option><option value="critical">Crítica</option></select></label><label><span>Resposta para a academia (opcional)</span><textarea rows={3} maxLength={2000} value={publicResponse} onChange={e=>setPublicResponse(e.target.value)}/></label><label><span>Nota interna (opcional)</span><textarea rows={3} maxLength={3000} value={internalNote} onChange={e=>setInternalNote(e.target.value)}/></label></div>}
      {mode==='reject'&&<div className="request-decision-fields"><label><span>Motivo visível para a academia *</span><textarea autoFocus rows={4} maxLength={2000} value={publicResponse} onChange={e=>setPublicResponse(e.target.value)}/></label><label><span>Nota interna (opcional)</span><textarea rows={3} maxLength={3000} value={internalNote} onChange={e=>setInternalNote(e.target.value)}/></label></div>}
      {mode==='convert'&&<div className="request-decision-fields"><label><span>Tipo *</span><select value={conversion.maintenanceType} onChange={e=>setConversion({...conversion,maintenanceType:e.target.value as RequestConversionInput['maintenanceType']})}><option value="corrective">Corretiva</option><option value="preventive">Preventiva</option></select></label><label><span>Data e hora do atendimento *</span><input type="datetime-local" value={conversion.scheduledAt} onChange={e=>setConversion({...conversion,scheduledAt:e.target.value})}/></label><label><span>Técnico responsável *</span><select value={conversion.responsibleTechnicianId} onChange={e=>setConversion({...conversion,responsibleTechnicianId:e.target.value})}><option value="">Selecione</option>{options.options.data?.technicians.map(t=><option key={t.user_id} value={t.user_id}>{t.full_name}</option>)}</select></label></div>}
      <div className="confirmation-actions"><button className="secondary-button" disabled={busy} onClick={closeDecision}>Voltar</button><button className="primary-button primary-button--compact" disabled={busy||mode==='convert'&&options.options.isLoading} onClick={()=>void act(mode)}>{busy?'Processando…':'Confirmar'}</button></div></div></section>}
    <section className="request-detail-section"><div className="request-section-heading"><div><span className="eyebrow">Storage privado</span><h2>Fotos anexadas</h2></div><span>{query.data.photos.length}</span></div>{query.data.photos.length?<div className="request-photo-gallery">{query.data.photos.map((photo,index)=><figure key={photo.id}><img src={photo.signed_url} alt={`Foto ${index+1} da solicitação`}/></figure>)}</div>:<p className="request-empty-copy">Nenhuma foto anexada.</p>}</section>
    {item.status==='cancelled'&&<section className="request-cancelled"><span>Cancelada em {item.cancelled_at?dateTime(item.cancelled_at):'—'}</span><p>{item.cancellation_reason}</p></section>}
  </section>
}
