import { useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { PageSkeleton, PageState } from '../../components/PageState'
import { useInternalRequestDetails, useInternalRequestList } from './maintenanceRequestQueries'
import type { RequestCriticality, RequestFilters } from './types'
import { criticalityLabel, requestStatusLabel } from './maintenanceRequestValidation'

function dateTime(value: string) { return new Intl.DateTimeFormat('pt-BR',{dateStyle:'medium',timeStyle:'short',timeZone:'America/Sao_Paulo'}).format(new Date(value)) }
function Badge({value,type}:{value:string;type:'status'|'criticality'}) { return <span className={`request-badge request-badge--${value}`}>{type==='status'?requestStatusLabel(value):criticalityLabel(value as RequestCriticality)}</span> }

export function InternalMaintenanceRequestListPage() {
  const [search,setSearch]=useState(''); const [filters,setFilters]=useState<RequestFilters>({status:'',criticality:''}); const [page,setPage]=useState(1)
  const {organization,query,deferred}=useInternalRequestList(search,filters,page); const loading=organization.isLoading||query.isLoading; const error=organization.error??query.error
  return <section className="clients-page internal-request-page" aria-labelledby="internal-requests-title"><div className="module-heading"><div><span className="eyebrow">Portal da Academia</span><h1 id="internal-requests-title">Solicitações</h1><p>Consulta dos relatos enviados pelas academias. Nenhuma solicitação cria uma OS automaticamente.</p></div></div>
    <div className="internal-request-toolbar"><label><span className="sr-only">Pesquisar solicitações</span><input type="search" value={search} onChange={(e)=>{setSearch(e.target.value);setPage(1)}} placeholder="Título, cliente ou equipamento"/></label><select aria-label="Filtrar por status" value={filters.status} onChange={(e)=>{setFilters({...filters,status:e.target.value});setPage(1)}}><option value="">Todos os status</option><option value="pending">Pendente</option><option value="cancelled">Cancelada</option></select><select aria-label="Filtrar por criticidade" value={filters.criticality} onChange={(e)=>{setFilters({...filters,criticality:e.target.value});setPage(1)}}><option value="">Todas as criticidades</option><option value="low">Baixa</option><option value="medium">Média</option><option value="high">Alta</option><option value="critical">Crítica</option></select></div>
    {loading&&<PageSkeleton rows={5}/>} {!loading&&error&&<PageState tone="error" title="Não foi possível carregar as solicitações" description={error instanceof Error?error.message:'Tente novamente.'} actionLabel="Tentar novamente" onAction={()=>void query.refetch()}/>} {!loading&&!error&&query.data?.items.length===0&&<PageState title={deferred||filters.status||filters.criticality?'Nenhuma solicitação encontrada':'Nenhuma solicitação recebida'} description={deferred||filters.status||filters.criticality?'Revise a busca e os filtros.':'As solicitações enviadas pelo Portal aparecerão aqui.'}/>} {Boolean(query.data?.items.length)&&<div className="internal-request-list"><div className="internal-request-list__head"><span>Solicitação</span><span>Academia / unidade</span><span>Estado</span><span>Recebida</span></div>{query.data?.items.map((item)=><Link to={`/app/solicitacoes/${item.id}`} key={item.id}><div><strong>{item.title}</strong><span>{item.equipment_name}</span></div><div><strong>{item.client_name}</strong><span>{item.location_name}</span></div><div className="request-card__meta"><Badge value={item.status} type="status"/><Badge value={item.reported_criticality} type="criticality"/></div><time dateTime={item.created_at}>{dateTime(item.created_at)}</time></Link>)}</div>}
    {query.data&&query.data.pageCount>1&&<nav className="portal-pagination" aria-label="Paginação"><button disabled={page===1} onClick={()=>setPage(page-1)}>← Anterior</button><span>Página <strong>{page}</strong> de {query.data.pageCount}</span><button disabled={page>=query.data.pageCount} onClick={()=>setPage(page+1)}>Próxima →</button></nav>}
  </section>
}

export function InternalMaintenanceRequestDetailsPage() {
  const {requestId}=useParams(); const navigate=useNavigate(); const {organization,query}=useInternalRequestDetails(requestId); const loading=organization.isLoading||query.isLoading; const error=organization.error??query.error
  if(loading)return <PageSkeleton rows={6}/>
  if(error||!query.data?.request)return <PageState tone="error" title="Solicitação indisponível" description={error instanceof Error?error.message:'Não encontrada neste tenant.'} actionLabel="Voltar" onAction={()=>navigate('/app/solicitacoes')}/>
  const item=query.data.request
  return <section className="clients-page internal-request-detail"><Link className="back-link" to="/app/solicitacoes">← Voltar para solicitações</Link><header className="detail-hero"><div><span className="eyebrow">Solicitação externa · somente leitura</span><h1>{item.title}</h1><p>{item.client_name} · {item.location_name}</p></div><div className="request-card__meta"><Badge value={item.status} type="status"/><Badge value={item.reported_criticality} type="criticality"/></div></header><div className="internal-request-detail__grid"><section><span className="eyebrow">Relato recebido</span><p>{item.description}</p></section><aside><dl><div><dt>Equipamento</dt><dd>{item.equipment_name}</dd></div><div><dt>Categoria</dt><dd>{item.equipment_category}</dd></div><div><dt>Solicitante</dt><dd>{item.requester_name}<small>{item.requester_email}</small></dd></div><div><dt>Recebida em</dt><dd>{dateTime(item.created_at)}</dd></div></dl></aside></div><section className="request-detail-section"><div className="request-section-heading"><div><span className="eyebrow">Storage privado</span><h2>Fotos anexadas</h2></div><span>{query.data.photos.length}</span></div>{query.data.photos.length?<div className="request-photo-gallery">{query.data.photos.map((photo,index)=><figure key={photo.id}><img src={photo.signed_url} alt={`Foto ${index+1} da solicitação`}/></figure>)}</div>:<p className="request-empty-copy">Nenhuma foto anexada.</p>}</section>{item.status==='cancelled'&&<section className="request-cancelled"><span>Cancelada em {item.cancelled_at?dateTime(item.cancelled_at):'—'}</span><p>{item.cancellation_reason}</p></section>}<div className="request-readonly-note"><strong>Fluxo independente</strong><span>Esta tela não aprova, rejeita, converte nem cria ordem de serviço.</span></div></section>
}
