begin;

create table public.maintenance_requests (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete restrict,
  client_id uuid not null,
  client_location_id uuid not null,
  equipment_id uuid not null,
  requested_by uuid not null,
  submission_key uuid not null,
  title text not null,
  description text not null,
  reported_criticality text not null,
  status text not null default 'pending',
  origin text not null default 'academy_portal',
  cancellation_reason text,
  cancelled_at timestamptz,
  cancelled_by uuid references auth.users (id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint maintenance_requests_id_organization_unique unique (id, organization_id),
  constraint maintenance_requests_submission_unique unique (requested_by, submission_key),
  constraint maintenance_requests_location_fk foreign key (client_location_id, client_id, organization_id)
    references public.client_locations (id, client_id, organization_id) on delete restrict,
  constraint maintenance_requests_equipment_fk foreign key (equipment_id, client_id, organization_id)
    references public.equipment (id, client_id, organization_id) on delete restrict,
  constraint maintenance_requests_requester_fk foreign key (requested_by, organization_id)
    references public.academy_portal_users (user_id, organization_id) on delete restrict,
  constraint maintenance_requests_title_check check (char_length(btrim(title)) between 5 and 160),
  constraint maintenance_requests_description_check check (char_length(btrim(description)) between 10 and 4000),
  constraint maintenance_requests_criticality_check check (reported_criticality in ('low', 'medium', 'high', 'critical')),
  constraint maintenance_requests_status_check check (status in ('pending', 'cancelled', 'approved', 'rejected', 'converted')),
  constraint maintenance_requests_origin_check check (origin = 'academy_portal'),
  constraint maintenance_requests_cancellation_check check (
    (status <> 'cancelled' and cancellation_reason is null and cancelled_at is null and cancelled_by is null)
    or (status = 'cancelled' and char_length(btrim(cancellation_reason)) between 3 and 500 and cancelled_at is not null and cancelled_by is not null)
  )
);

create index maintenance_requests_portal_list_idx
  on public.maintenance_requests (requested_by, client_location_id, created_at desc, id);
create index maintenance_requests_internal_list_idx
  on public.maintenance_requests (organization_id, status, created_at desc, id);

create table public.maintenance_request_photos (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete restrict,
  maintenance_request_id uuid not null,
  bucket_id text not null default 'maintenance-request-photos',
  storage_path text not null,
  mime_type text not null,
  file_size bigint not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  created_by uuid not null references auth.users (id) on delete restrict,
  removed_at timestamptz,
  removed_by uuid references auth.users (id) on delete restrict,
  constraint maintenance_request_photos_request_fk foreign key (maintenance_request_id, organization_id)
    references public.maintenance_requests (id, organization_id) on delete restrict,
  constraint maintenance_request_photos_path_unique unique (bucket_id, storage_path),
  constraint maintenance_request_photos_bucket_check check (bucket_id = 'maintenance-request-photos'),
  constraint maintenance_request_photos_mime_check check (mime_type in ('image/webp', 'image/jpeg')),
  constraint maintenance_request_photos_size_check check (file_size between 1 and 10485760),
  constraint maintenance_request_photos_order_check check (sort_order between 0 and 4),
  constraint maintenance_request_photos_removal_check check ((removed_at is null) = (removed_by is null)),
  constraint maintenance_request_photos_path_check check (
    storage_path = organization_id::text || '/' || maintenance_request_id::text || '/' || created_by::text || '/' || split_part(storage_path, '/', 4)
    and split_part(storage_path, '/', 4) <> ''
  )
);

create unique index maintenance_request_photos_active_order_uidx
  on public.maintenance_request_photos (maintenance_request_id, sort_order) where removed_at is null;

create table public.maintenance_request_events (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations (id) on delete restrict,
  maintenance_request_id uuid not null,
  action text not null,
  actor_id uuid not null references auth.users (id) on delete restrict,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint maintenance_request_events_request_fk foreign key (maintenance_request_id, organization_id)
    references public.maintenance_requests (id, organization_id) on delete restrict,
  constraint maintenance_request_events_action_check check (action in ('request_created', 'photo_added', 'photo_removed', 'request_cancelled')),
  constraint maintenance_request_events_details_check check (jsonb_typeof(details) = 'object' and pg_column_size(details) <= 4096)
);

create index maintenance_request_events_request_idx
  on public.maintenance_request_events (maintenance_request_id, created_at, id);
create unique index maintenance_request_events_created_once_uidx
  on public.maintenance_request_events (maintenance_request_id) where action = 'request_created';
create unique index maintenance_request_events_cancelled_once_uidx
  on public.maintenance_request_events (maintenance_request_id) where action = 'request_cancelled';

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('maintenance-request-photos', 'maintenance-request-photos', false, 10485760, array['image/webp', 'image/jpeg']::text[])
on conflict (id) do update set public = false, file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create or replace function public.guard_maintenance_request_records()
returns trigger language plpgsql set search_path = '' as $$
begin
  if tg_op = 'DELETE' then
    raise exception using errcode = '42501', message = 'Solicitacoes de manutencao nao podem ser excluidas.';
  end if;
  if tg_op = 'UPDATE' and (
    new.id is distinct from old.id or new.organization_id is distinct from old.organization_id
    or new.client_id is distinct from old.client_id or new.client_location_id is distinct from old.client_location_id
    or new.equipment_id is distinct from old.equipment_id or new.requested_by is distinct from old.requested_by
    or new.submission_key is distinct from old.submission_key or new.title is distinct from old.title
    or new.description is distinct from old.description or new.reported_criticality is distinct from old.reported_criticality
    or new.origin is distinct from old.origin or new.created_at is distinct from old.created_at
    or old.status <> 'pending' or new.status <> 'cancelled'
  ) then
    raise exception using errcode = '42501', message = 'A solicitacao enviada e imutavel.';
  end if;
  return new;
end;
$$;

create trigger maintenance_requests_guard before update or delete on public.maintenance_requests
for each row execute function public.guard_maintenance_request_records();

create or replace function public.guard_maintenance_request_history()
returns trigger language plpgsql set search_path = '' as $$
begin
  raise exception using errcode = '42501', message = 'O historico da solicitacao e imutavel.';
end;
$$;
create trigger maintenance_request_events_guard before update or delete on public.maintenance_request_events
for each row execute function public.guard_maintenance_request_history();

create or replace function public.current_academy_request_scope(target_client_location_id uuid)
returns table (organization_id uuid, client_id uuid, client_location_id uuid, location_name text)
language sql stable security definer set search_path = '' as $$
  select scope.organization_id, scope.client_id, scope.client_location_id, scope.location_name
  from public.current_academy_equipment_scope(target_client_location_id) scope;
$$;

create or replace function public.maintenance_request_scope_is_current(target_request_id uuid, target_location_id uuid, target_actor_id uuid)
returns boolean language plpgsql stable security definer set search_path = '' as $$
begin
  return exists (
    select 1 from public.maintenance_requests requests
    join public.current_academy_request_scope(target_location_id) scope
      on scope.organization_id = requests.organization_id and scope.client_id = requests.client_id
      and scope.client_location_id = requests.client_location_id
    join public.equipment equipment on equipment.id = requests.equipment_id
      and equipment.organization_id = requests.organization_id and equipment.client_id = requests.client_id
      and equipment.client_location_id = requests.client_location_id and equipment.deleted_at is null
    where requests.id = target_request_id and requests.requested_by = target_actor_id
  );
exception
  when sqlstate '42501' then
    return false;
end;
$$;

create or replace function public.is_internal_maintenance_request_member(target_organization_id uuid)
returns boolean language sql stable security definer set search_path = '' as $$
  select auth.uid() is not null
    and not exists (
      select 1
      from public.academy_portal_users as portal_users
      where portal_users.user_id = auth.uid()
    )
    and exists (
      select 1
      from public.organization_members as members
      where members.organization_id = target_organization_id
        and members.user_id = auth.uid()
        and members.role in ('owner', 'technician')
        and members.status = 'active'
    );
$$;

create or replace function public.can_access_maintenance_request(target_request_id uuid, target_location_id uuid)
returns boolean language sql stable security definer set search_path = '' as $$
  select auth.uid() is not null
    and public.maintenance_request_scope_is_current(target_request_id, target_location_id, auth.uid());
$$;

create or replace function public.portal_create_maintenance_request(
  target_client_location_id uuid, target_equipment_id uuid, request_title text,
  request_description text, request_criticality text, request_submission_key uuid
) returns uuid language plpgsql security definer set search_path = '' as $$
declare actor_id uuid := auth.uid(); scope_record record; new_id uuid; existing_id uuid;
begin
  if request_submission_key is null then raise exception using errcode = '22023', message = 'Identificador de envio invalido.'; end if;
  select * into scope_record from public.current_academy_request_scope(target_client_location_id);
  if not exists (select 1 from public.equipment e where e.id = target_equipment_id
    and e.organization_id = scope_record.organization_id and e.client_id = scope_record.client_id
    and e.client_location_id = scope_record.client_location_id and e.deleted_at is null and e.status <> 'inactive') then
    raise exception using errcode = '42501', message = 'Equipamento indisponivel nesta unidade.';
  end if;
  if char_length(btrim(coalesce(request_title,''))) not between 5 and 160 then raise exception using errcode='22023', message='Informe um titulo entre 5 e 160 caracteres.'; end if;
  if char_length(btrim(coalesce(request_description,''))) not between 10 and 4000 then raise exception using errcode='22023', message='Informe uma descricao entre 10 e 4000 caracteres.'; end if;
  if request_criticality not in ('low','medium','high','critical') then raise exception using errcode='22023', message='Criticidade percebida invalida.'; end if;
  select id into existing_id from public.maintenance_requests where requested_by=actor_id and submission_key=request_submission_key;
  if existing_id is not null then return existing_id; end if;
  insert into public.maintenance_requests (organization_id,client_id,client_location_id,equipment_id,requested_by,submission_key,title,description,reported_criticality)
  values (scope_record.organization_id,scope_record.client_id,scope_record.client_location_id,target_equipment_id,actor_id,request_submission_key,btrim(request_title),btrim(request_description),request_criticality)
  returning id into new_id;
  insert into public.maintenance_request_events (organization_id,maintenance_request_id,action,actor_id)
  values (scope_record.organization_id,new_id,'request_created',actor_id);
  return new_id;
exception when unique_violation then
  select id into existing_id from public.maintenance_requests where requested_by=actor_id and submission_key=request_submission_key;
  if existing_id is not null then return existing_id; end if; raise;
end;
$$;

create or replace function public.portal_list_maintenance_requests(
  target_client_location_id uuid, search_term text default null, filter_status text default null,
  filter_criticality text default null, page_number integer default 1, page_size integer default 12
) returns table (id uuid,title text,description text,reported_criticality text,status text,equipment_id uuid,equipment_name text,created_at timestamptz,total_count bigint)
language plpgsql stable security definer set search_path = '' as $$
declare actor_id uuid:=auth.uid(); scope_record record; q text:=nullif(btrim(coalesce(search_term,'')),''); p int:=greatest(coalesce(page_number,1),1); s int:=least(greatest(coalesce(page_size,12),1),50);
begin
  select * into scope_record from public.current_academy_request_scope(target_client_location_id);
  return query select r.id,r.title,r.description,r.reported_criticality,r.status,r.equipment_id,e.name,r.created_at,count(*) over()::bigint
  from public.maintenance_requests r join public.equipment e on e.id=r.equipment_id and e.organization_id=r.organization_id
  where r.organization_id=scope_record.organization_id and r.client_id=scope_record.client_id and r.client_location_id=scope_record.client_location_id
    and r.requested_by=actor_id and (q is null or r.title ilike '%'||q||'%' or e.name ilike '%'||q||'%')
    and (nullif(filter_status,'') is null or r.status=filter_status) and (nullif(filter_criticality,'') is null or r.reported_criticality=filter_criticality)
  order by r.created_at desc,r.id limit s offset (p-1)*s;
end;
$$;

create or replace function public.portal_get_maintenance_request(target_client_location_id uuid,target_request_id uuid)
returns table (id uuid,title text,description text,reported_criticality text,status text,equipment_id uuid,equipment_name text,equipment_category text,location_name text,created_at timestamptz,cancellation_reason text,cancelled_at timestamptz)
language plpgsql stable security definer set search_path = '' as $$
declare actor_id uuid:=auth.uid(); scope_record record;
begin
  select * into scope_record from public.current_academy_request_scope(target_client_location_id);
  return query select r.id,r.title,r.description,r.reported_criticality,r.status,r.equipment_id,e.name,e.category,scope_record.location_name,r.created_at,r.cancellation_reason,r.cancelled_at
  from public.maintenance_requests r join public.equipment e on e.id=r.equipment_id and e.organization_id=r.organization_id
  where r.id=target_request_id and r.organization_id=scope_record.organization_id and r.client_id=scope_record.client_id
    and r.client_location_id=scope_record.client_location_id and r.requested_by=actor_id;
end;
$$;

create or replace function public.portal_cancel_maintenance_request(target_client_location_id uuid,target_request_id uuid,cancel_reason text)
returns void language plpgsql security definer set search_path = '' as $$
declare actor_id uuid:=auth.uid(); scope_record record; current_status text;
begin
  select * into scope_record from public.current_academy_request_scope(target_client_location_id);
  if char_length(btrim(coalesce(cancel_reason,''))) not between 3 and 500 then raise exception using errcode='22023',message='Informe um motivo entre 3 e 500 caracteres.'; end if;
  select status into current_status from public.maintenance_requests where id=target_request_id and organization_id=scope_record.organization_id
    and client_id=scope_record.client_id and client_location_id=scope_record.client_location_id and requested_by=actor_id for update;
  if not found then raise exception using errcode='42501',message='Solicitacao indisponivel.'; end if;
  if current_status='cancelled' then return; end if;
  if current_status<>'pending' then raise exception using errcode='42501',message='Somente solicitacoes pendentes podem ser canceladas.'; end if;
  update public.maintenance_requests set status='cancelled',cancellation_reason=btrim(cancel_reason),cancelled_at=now(),cancelled_by=actor_id,updated_at=now() where id=target_request_id;
  insert into public.maintenance_request_events(organization_id,maintenance_request_id,action,actor_id,details)
  values(scope_record.organization_id,target_request_id,'request_cancelled',actor_id,jsonb_build_object('reason',btrim(cancel_reason)))
  on conflict (maintenance_request_id) where action = 'request_cancelled' do nothing;
end;
$$;

create or replace function public.portal_register_maintenance_request_photo(target_client_location_id uuid,target_request_id uuid,target_storage_path text,target_mime_type text,target_file_size bigint,target_sort_order integer)
returns uuid language plpgsql security definer set search_path = '' as $$
declare actor_id uuid:=auth.uid(); scope_record record; photo_id uuid;
begin
  select * into scope_record from public.current_academy_request_scope(target_client_location_id);
  perform 1 from public.maintenance_requests r where r.id=target_request_id and r.organization_id=scope_record.organization_id and r.client_location_id=scope_record.client_location_id and r.requested_by=actor_id and r.status='pending' for update;
  if not found then raise exception using errcode='42501',message='Fotos so podem ser adicionadas a uma solicitacao pendente.'; end if;
  if not public.maintenance_request_scope_is_current(target_request_id,target_client_location_id,actor_id) then raise exception using errcode='42501',message='Acesso a solicitacao indisponivel.'; end if;
  if target_mime_type not in ('image/webp','image/jpeg') or target_file_size not between 1 and 10485760 or target_sort_order not between 0 and 4 then raise exception using errcode='22023',message='Metadados da foto invalidos.'; end if;
  if target_storage_path <> scope_record.organization_id::text||'/'||target_request_id::text||'/'||actor_id::text||'/'||split_part(target_storage_path,'/',4) or split_part(target_storage_path,'/',4)='' then raise exception using errcode='22023',message='Caminho da foto invalido.'; end if;
  if not exists(select 1 from storage.objects where bucket_id='maintenance-request-photos' and name=target_storage_path and owner_id=actor_id::text) then raise exception using errcode='23503',message='Arquivo privado nao encontrado no Storage.'; end if;
  if (select count(*) from public.maintenance_request_photos where maintenance_request_id=target_request_id and removed_at is null)>=5 then raise exception using errcode='23514',message='Cada solicitacao aceita no maximo 5 fotos.'; end if;
  insert into public.maintenance_request_photos(organization_id,maintenance_request_id,storage_path,mime_type,file_size,sort_order,created_by)
  values(scope_record.organization_id,target_request_id,target_storage_path,target_mime_type,target_file_size,target_sort_order,actor_id) returning id into photo_id;
  insert into public.maintenance_request_events(organization_id,maintenance_request_id,action,actor_id,details) values(scope_record.organization_id,target_request_id,'photo_added',actor_id,jsonb_build_object('photo_id',photo_id));
  return photo_id;
end;
$$;

create or replace function public.portal_get_maintenance_request_upload_prefix(target_client_location_id uuid,target_request_id uuid)
returns text language plpgsql stable security definer set search_path='' as $$
declare actor_id uuid:=auth.uid(); request_organization_id uuid;
begin
  if not public.maintenance_request_scope_is_current(target_request_id,target_client_location_id,actor_id) then
    raise exception using errcode='42501',message='Upload indisponivel.';
  end if;
  select organization_id into request_organization_id from public.maintenance_requests
  where id=target_request_id and requested_by=actor_id and status='pending';
  if not found then raise exception using errcode='42501',message='Upload indisponivel.'; end if;
  return request_organization_id::text||'/'||target_request_id::text||'/'||actor_id::text;
end;
$$;

create or replace function public.portal_remove_maintenance_request_photo(target_client_location_id uuid,target_request_id uuid,target_photo_id uuid)
returns text language plpgsql security definer set search_path = '' as $$
declare actor_id uuid:=auth.uid(); scope_record record; result_path text; current_status text;
begin
  select * into scope_record from public.current_academy_request_scope(target_client_location_id);
  select status into current_status from public.maintenance_requests where id=target_request_id and organization_id=scope_record.organization_id and client_location_id=scope_record.client_location_id and requested_by=actor_id for update;
  if not found or current_status<>'pending' then raise exception using errcode='42501',message='Fotos so podem ser removidas de uma solicitacao pendente.'; end if;
  select storage_path into result_path from public.maintenance_request_photos where id=target_photo_id and maintenance_request_id=target_request_id and organization_id=scope_record.organization_id and created_by=actor_id;
  if not found then raise exception using errcode='42501',message='Foto indisponivel.'; end if;
  update public.maintenance_request_photos set removed_at=coalesce(removed_at,now()),removed_by=coalesce(removed_by,actor_id) where id=target_photo_id;
  if not exists(select 1 from public.maintenance_request_events where maintenance_request_id=target_request_id and action='photo_removed' and details->>'photo_id'=target_photo_id::text) then
    insert into public.maintenance_request_events(organization_id,maintenance_request_id,action,actor_id,details) values(scope_record.organization_id,target_request_id,'photo_removed',actor_id,jsonb_build_object('photo_id',target_photo_id));
  end if;
  return result_path;
end;
$$;

create or replace function public.portal_list_maintenance_request_photos(target_client_location_id uuid,target_request_id uuid)
returns table(id uuid,bucket_id text,storage_path text,mime_type text,file_size bigint,sort_order integer,created_at timestamptz)
language plpgsql stable security definer set search_path='' as $$
declare actor_id uuid:=auth.uid();
begin
  if not public.maintenance_request_scope_is_current(target_request_id,target_client_location_id,actor_id) then raise exception using errcode='42501',message='Fotos indisponiveis.'; end if;
  return query select p.id,p.bucket_id,p.storage_path,p.mime_type,p.file_size,p.sort_order,p.created_at from public.maintenance_request_photos p where p.maintenance_request_id=target_request_id and p.created_by=actor_id and p.removed_at is null order by p.sort_order,p.created_at,p.id;
end;
$$;

create or replace function public.internal_list_maintenance_requests(target_organization_id uuid,search_term text default null,filter_status text default null,filter_criticality text default null,page_number integer default 1,page_size integer default 20)
returns table(id uuid,title text,description text,reported_criticality text,status text,equipment_name text,client_name text,location_name text,requester_name text,created_at timestamptz,total_count bigint)
language plpgsql stable security definer set search_path='' as $$
declare q text:=nullif(btrim(coalesce(search_term,'')),''); p int:=greatest(coalesce(page_number,1),1); s int:=least(greatest(coalesce(page_size,20),1),50);
begin
  if not public.is_internal_maintenance_request_member(target_organization_id) then raise exception using errcode='42501',message='Acesso negado.'; end if;
  return query select r.id,r.title,r.description,r.reported_criticality,r.status,e.name,c.name,l.name,profiles.full_name,r.created_at,count(*) over()::bigint
  from public.maintenance_requests r join public.equipment e on e.id=r.equipment_id and e.organization_id=r.organization_id
  join public.clients c on c.id=r.client_id and c.organization_id=r.organization_id join public.client_locations l on l.id=r.client_location_id and l.organization_id=r.organization_id
  join public.profiles on profiles.id=r.requested_by where r.organization_id=target_organization_id
  and (q is null or r.title ilike '%'||q||'%' or e.name ilike '%'||q||'%' or c.name ilike '%'||q||'%')
  and (nullif(filter_status,'') is null or r.status=filter_status) and (nullif(filter_criticality,'') is null or r.reported_criticality=filter_criticality)
  order by r.created_at desc,r.id limit s offset (p-1)*s;
end;
$$;

create or replace function public.internal_get_maintenance_request(target_organization_id uuid,target_request_id uuid)
returns table(id uuid,title text,description text,reported_criticality text,status text,equipment_name text,equipment_category text,client_name text,location_name text,requester_name text,requester_email text,created_at timestamptz,cancellation_reason text,cancelled_at timestamptz)
language plpgsql stable security definer set search_path='' as $$
begin
  if not public.is_internal_maintenance_request_member(target_organization_id) then raise exception using errcode='42501',message='Acesso negado.'; end if;
  return query select r.id,r.title,r.description,r.reported_criticality,r.status,e.name,e.category,c.name,l.name,p.full_name,u.email::text,r.created_at,r.cancellation_reason,r.cancelled_at
  from public.maintenance_requests r join public.equipment e on e.id=r.equipment_id and e.organization_id=r.organization_id
  join public.clients c on c.id=r.client_id and c.organization_id=r.organization_id join public.client_locations l on l.id=r.client_location_id and l.organization_id=r.organization_id
  join public.profiles p on p.id=r.requested_by join auth.users u on u.id=r.requested_by where r.id=target_request_id and r.organization_id=target_organization_id;
end;
$$;

create or replace function public.internal_list_maintenance_request_photos(target_organization_id uuid,target_request_id uuid)
returns table(id uuid,bucket_id text,storage_path text,mime_type text,file_size bigint,sort_order integer,created_at timestamptz)
language plpgsql stable security definer set search_path='' as $$
begin
  if not public.is_internal_maintenance_request_member(target_organization_id) then raise exception using errcode='42501',message='Acesso negado.'; end if;
  return query select p.id,p.bucket_id,p.storage_path,p.mime_type,p.file_size,p.sort_order,p.created_at from public.maintenance_request_photos p where p.organization_id=target_organization_id and p.maintenance_request_id=target_request_id and p.removed_at is null order by p.sort_order,p.created_at,p.id;
end;
$$;

create or replace function public.can_access_maintenance_request_photo_object(object_name text,require_pending boolean default false)
returns boolean language sql stable security definer set search_path='' as $$
  select exists(select 1 from public.maintenance_requests r where r.organization_id::text=split_part(object_name,'/',1) and r.id::text=split_part(object_name,'/',2)
    and r.requested_by::text=split_part(object_name,'/',3) and split_part(object_name,'/',4)<>'' and object_name=split_part(object_name,'/',1)||'/'||split_part(object_name,'/',2)||'/'||split_part(object_name,'/',3)||'/'||split_part(object_name,'/',4)
    and (public.is_internal_maintenance_request_member(r.organization_id) or (r.requested_by=auth.uid() and public.maintenance_request_scope_is_current(r.id,r.client_location_id,auth.uid())))
    and (not require_pending or r.status='pending'));
$$;

create or replace function public.can_delete_maintenance_request_photo_object(object_name text)
returns boolean language plpgsql volatile security definer set search_path='' as $$
declare
  actor_id uuid := auth.uid();
  path_parts text[] := string_to_array(object_name, '/');
  request_record record;
  photo_record record;
begin
  if actor_id is null
    or object_name is null
    or cardinality(path_parts) <> 4
    or path_parts[1] = ''
    or path_parts[2] = ''
    or path_parts[3] = ''
    or path_parts[4] = ''
    or object_name <> path_parts[1] || '/' || path_parts[2] || '/' || path_parts[3] || '/' || path_parts[4]
  then
    return false;
  end if;

  select requests.id, requests.organization_id, requests.requested_by
  into request_record
  from public.maintenance_requests as requests
  where requests.organization_id::text = path_parts[1]
    and requests.id::text = path_parts[2]
    and requests.requested_by = actor_id
    and requests.requested_by::text = path_parts[3]
  for update;

  if not found then
    return false;
  end if;

  if not exists (
    select 1
    from storage.objects as objects
    where objects.bucket_id = 'maintenance-request-photos'
      and objects.name = object_name
      and objects.owner_id = actor_id::text
  ) then
    return false;
  end if;

  select photos.organization_id, photos.maintenance_request_id, photos.created_by,
    photos.removed_at, photos.removed_by
  into photo_record
  from public.maintenance_request_photos as photos
  where photos.bucket_id = 'maintenance-request-photos'
    and photos.storage_path = object_name;

  if not found then
    -- Compensacao de upload proprio ainda sem metadado. O lock da solicitacao
    -- serializa esta decisao com portal_register_maintenance_request_photo().
    return true;
  end if;

  -- Uma foto vinculada so pode ser removida depois do tombstone emitido pela RPC.
  return photo_record.organization_id = request_record.organization_id
    and photo_record.maintenance_request_id = request_record.id
    and photo_record.created_by = actor_id
    and photo_record.removed_at is not null
    and photo_record.removed_by = actor_id;
end;
$$;

alter table public.maintenance_requests enable row level security;
alter table public.maintenance_request_photos enable row level security;
alter table public.maintenance_request_events enable row level security;
create policy maintenance_requests_select_scoped on public.maintenance_requests for select to authenticated using (public.is_internal_maintenance_request_member(organization_id) or (requested_by=auth.uid() and public.can_access_maintenance_request(id,client_location_id)));
create policy maintenance_request_photos_select_scoped on public.maintenance_request_photos for select to authenticated using (removed_at is null and (public.is_internal_maintenance_request_member(organization_id) or exists(select 1 from public.maintenance_requests r where r.id=maintenance_request_id and r.requested_by=auth.uid() and public.can_access_maintenance_request(r.id,r.client_location_id))));
create policy maintenance_request_events_select_internal on public.maintenance_request_events for select to authenticated using (public.is_internal_maintenance_request_member(organization_id));

revoke all on table public.maintenance_requests,public.maintenance_request_photos,public.maintenance_request_events from anon,authenticated;
grant select on table public.maintenance_requests,public.maintenance_request_photos,public.maintenance_request_events to service_role;

-- A API oficial de remocao do Storage exige SELECT e DELETE. A segunda clausula
-- libera a selecao tecnica somente para o proprio orfao elegivel ou tombstone;
-- fotos vinculadas e preservadas continuam excluidas por can_delete(...)=false.
create policy maintenance_request_objects_select on storage.objects for select to authenticated using(bucket_id='maintenance-request-photos' and (public.can_access_maintenance_request_photo_object(name,false) or public.can_delete_maintenance_request_photo_object(name)));
create policy maintenance_request_objects_insert on storage.objects for insert to authenticated with check(bucket_id='maintenance-request-photos' and (lower(name)~'\.(webp|jpg|jpeg)$') and public.can_access_maintenance_request_photo_object(name,true));
create policy maintenance_request_objects_delete on storage.objects for delete to authenticated using(bucket_id='maintenance-request-photos' and public.can_delete_maintenance_request_photo_object(name));

revoke all on function public.guard_maintenance_request_records(),public.guard_maintenance_request_history(),public.current_academy_request_scope(uuid),public.maintenance_request_scope_is_current(uuid,uuid,uuid),public.is_internal_maintenance_request_member(uuid),public.can_access_maintenance_request(uuid,uuid),public.can_access_maintenance_request_photo_object(text,boolean),public.can_delete_maintenance_request_photo_object(text) from public,anon,authenticated;
grant execute on function public.is_internal_maintenance_request_member(uuid),public.can_access_maintenance_request(uuid,uuid),public.can_access_maintenance_request_photo_object(text,boolean),public.can_delete_maintenance_request_photo_object(text) to authenticated;
revoke all on function public.portal_create_maintenance_request(uuid,uuid,text,text,text,uuid),public.portal_list_maintenance_requests(uuid,text,text,text,integer,integer),public.portal_get_maintenance_request(uuid,uuid),public.portal_cancel_maintenance_request(uuid,uuid,text),public.portal_register_maintenance_request_photo(uuid,uuid,text,text,bigint,integer),public.portal_get_maintenance_request_upload_prefix(uuid,uuid),public.portal_remove_maintenance_request_photo(uuid,uuid,uuid),public.portal_list_maintenance_request_photos(uuid,uuid),public.internal_list_maintenance_requests(uuid,text,text,text,integer,integer),public.internal_get_maintenance_request(uuid,uuid),public.internal_list_maintenance_request_photos(uuid,uuid) from public,anon;
grant execute on function public.portal_create_maintenance_request(uuid,uuid,text,text,text,uuid),public.portal_list_maintenance_requests(uuid,text,text,text,integer,integer),public.portal_get_maintenance_request(uuid,uuid),public.portal_cancel_maintenance_request(uuid,uuid,text),public.portal_register_maintenance_request_photo(uuid,uuid,text,text,bigint,integer),public.portal_get_maintenance_request_upload_prefix(uuid,uuid),public.portal_remove_maintenance_request_photo(uuid,uuid,uuid),public.portal_list_maintenance_request_photos(uuid,uuid),public.internal_list_maintenance_requests(uuid,text,text,text,integer,integer),public.internal_get_maintenance_request(uuid,uuid),public.internal_list_maintenance_request_photos(uuid,uuid) to authenticated;

-- Etapa 13: ausencia deve ser um resultado controlado, nunca HTTP 500/P0002.
create or replace function public.portal_get_equipment(target_client_location_id uuid,target_equipment_id uuid)
returns table(id uuid,name text,category text,brand text,model text,serial_number text,asset_tag text,status text,notes text,created_at timestamptz,location_name text,created_source text)
language plpgsql stable security definer set search_path='' as $$
declare scope_record record;
begin
  select * into scope_record from public.current_academy_equipment_scope(target_client_location_id);
  return query select e.id,e.name,e.category,e.brand,e.model,e.serial_number,e.asset_tag,e.status,case when e.created_source='academy_portal' then e.notes else null end,e.created_at,scope_record.location_name,e.created_source
  from public.equipment e where e.id=target_equipment_id and e.organization_id=scope_record.organization_id and e.client_id=scope_record.client_id and e.client_location_id=scope_record.client_location_id and e.deleted_at is null;
end;
$$;

comment on table public.maintenance_requests is 'Solicitacoes externas imutaveis do Portal, independentes de ordens de servico.';
comment on table public.maintenance_request_photos is 'Somente metadados de fotos privadas; binarios permanecem exclusivamente no Storage.';
comment on column public.maintenance_requests.reported_criticality is 'Percepcao informada pela academia; nao representa classificacao tecnica da Zion.';

commit;
