begin;

create table public.academy_portal_audit_events (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations (id) on delete restrict,
  user_id uuid,
  client_id uuid,
  client_location_id uuid,
  action text not null,
  previous_state jsonb not null default '{}'::jsonb,
  next_state jsonb not null default '{}'::jsonb,
  reason text not null,
  performed_by uuid not null,
  created_at timestamptz not null default now(),
  constraint academy_portal_audit_events_user_fk
    foreign key (user_id, organization_id)
    references public.academy_portal_users (user_id, organization_id)
    on delete restrict,
  constraint academy_portal_audit_events_client_fk
    foreign key (client_id, organization_id)
    references public.clients (id, organization_id)
    on delete restrict,
  constraint academy_portal_audit_events_location_fk
    foreign key (client_location_id, client_id, organization_id)
    references public.client_locations (id, client_id, organization_id)
    on delete restrict,
  constraint academy_portal_audit_events_actor_fk
    foreign key (organization_id, performed_by)
    references public.organization_members (organization_id, user_id)
    on delete restrict,
  constraint academy_portal_audit_events_action_check check (
    action in (
      'initial_configuration_completed',
      'user_activated',
      'user_suspended',
      'user_reactivated',
      'user_downgraded_no_locations',
      'location_granted',
      'location_revoked',
      'location_reactivated',
      'commercial_access_changed'
    )
  ),
  constraint academy_portal_audit_events_reason_length_check check (
    char_length(btrim(reason)) between 3 and 500
  ),
  constraint academy_portal_audit_events_state_shape_check check (
    jsonb_typeof(previous_state) = 'object'
    and jsonb_typeof(next_state) = 'object'
    and octet_length(previous_state::text) <= 4096
    and octet_length(next_state::text) <= 4096
  ),
  constraint academy_portal_audit_events_location_requires_client_check check (
    client_location_id is null or client_id is not null
  )
);

create index academy_portal_audit_events_organization_created_idx
  on public.academy_portal_audit_events (organization_id, created_at desc, id desc);
create index academy_portal_audit_events_user_created_idx
  on public.academy_portal_audit_events (organization_id, user_id, created_at desc, id desc)
  where user_id is not null;
create index academy_portal_audit_events_client_created_idx
  on public.academy_portal_audit_events (organization_id, client_id, created_at desc, id desc)
  where client_id is not null;

create or replace function public.guard_academy_portal_audit_event()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if tg_op <> 'INSERT' then
    raise exception using errcode = '42501', message = 'O histórico administrativo é imutável.';
  end if;
  if coalesce(current_setting('zion.academy_administration', true), '') <> 'allowed' then
    raise exception using errcode = '42501', message = 'Registre auditoria somente pelas operações administrativas.';
  end if;
  return new;
end;
$$;

create trigger academy_portal_audit_events_guard
before insert or update or delete on public.academy_portal_audit_events
for each row execute function public.guard_academy_portal_audit_event();

alter table public.academy_portal_audit_events enable row level security;

create policy "academy_portal_audit_events_select_owner"
on public.academy_portal_audit_events
for select to authenticated
using (public.is_organization_owner(organization_id));

revoke all on table public.academy_portal_audit_events from anon, authenticated;
grant select on table public.academy_portal_audit_events to authenticated;

create or replace function public.current_academy_admin_organization_id()
returns uuid
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  actor_id uuid := auth.uid();
  organization_count integer;
  resolved_organization_id uuid;
begin
  if actor_id is null then
    raise exception using errcode = '42501', message = 'Autenticação obrigatória.';
  end if;

  select count(*), min(members.organization_id::text)::uuid
  into organization_count, resolved_organization_id
  from public.organization_members as members
  join public.organizations
    on organizations.id = members.organization_id
    and organizations.status = 'active'
  where members.user_id = actor_id
    and members.role = 'owner'
    and members.status = 'active';

  if organization_count <> 1 then
    raise exception using
      errcode = '42501',
      message = 'A administração do Portal exige exatamente um vínculo owner ativo.';
  end if;

  return resolved_organization_id;
end;
$$;

create or replace function public.record_academy_portal_audit_event(
  target_organization_id uuid,
  target_user_id uuid,
  target_client_id uuid,
  target_client_location_id uuid,
  target_action text,
  target_previous_state jsonb,
  target_next_state jsonb,
  target_reason text,
  target_actor_id uuid
)
returns void
language sql
security definer
set search_path = ''
as $$
  insert into public.academy_portal_audit_events (
    organization_id,
    user_id,
    client_id,
    client_location_id,
    action,
    previous_state,
    next_state,
    reason,
    performed_by
  ) values (
    target_organization_id,
    target_user_id,
    target_client_id,
    target_client_location_id,
    target_action,
    coalesce(target_previous_state, '{}'::jsonb),
    coalesce(target_next_state, '{}'::jsonb),
    btrim(target_reason),
    target_actor_id
  );
$$;

create or replace function public.get_academy_portal_admin_summary()
returns table (
  pending_users bigint,
  active_users bigint,
  suspended_users bigint,
  active_academies bigint
)
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  owner_organization_id uuid := public.current_academy_admin_organization_id();
begin
  return query
  select
    count(*) filter (where portal_users.status = 'pending'),
    count(*) filter (where portal_users.status = 'active' and portal_users.organization_id = owner_organization_id),
    count(*) filter (where portal_users.status = 'suspended' and portal_users.organization_id = owner_organization_id),
    (
      select count(*)
      from public.academy_portal_access
      where organization_id = owner_organization_id
        and status in ('trialing', 'active')
    )
  from public.academy_portal_users as portal_users
  where portal_users.organization_id = owner_organization_id
    or (portal_users.organization_id is null and portal_users.status = 'pending');
end;
$$;

create or replace function public.list_academy_portal_admin_users(
  search_term text default null,
  filter_status text default null,
  filter_client_id uuid default null,
  page_size integer default 25,
  page_offset integer default 0
)
returns table (
  user_id uuid,
  full_name text,
  email text,
  email_confirmed boolean,
  auth_disabled boolean,
  portal_status text,
  organization_id uuid,
  client_id uuid,
  client_name text,
  active_location_count bigint,
  commercial_status text,
  created_at timestamptz,
  updated_at timestamptz,
  total_count bigint
)
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  owner_organization_id uuid := public.current_academy_admin_organization_id();
  normalized_search text := lower(btrim(coalesce(search_term, '')));
  normalized_status text := nullif(btrim(coalesce(filter_status, '')), '');
  safe_page_size integer := greatest(1, least(coalesce(page_size, 25), 100));
  safe_page_offset integer := greatest(0, coalesce(page_offset, 0));
begin
  if normalized_status is not null and normalized_status not in ('pending', 'active', 'suspended') then
    raise exception using errcode = '22023', message = 'Filtro de status inválido.';
  end if;

  return query
  with visible_users as (
    select
      portal_users.user_id,
      profiles.full_name,
      auth_users.email::text,
      auth_users.email_confirmed_at is not null as email_confirmed,
      auth_users.banned_until is not null and auth_users.banned_until > now() as auth_disabled,
      portal_users.status as portal_status,
      portal_users.organization_id,
      linked_client.client_id,
      clients.name as client_name,
      coalesce(linked_client.active_location_count, 0::bigint) as active_location_count,
      commercial.status as commercial_status,
      portal_users.created_at,
      portal_users.updated_at
    from public.academy_portal_users as portal_users
    join auth.users as auth_users on auth_users.id = portal_users.user_id
    left join public.profiles on profiles.id = portal_users.user_id
    left join lateral (
      select
        coalesce(
          min(links.client_id::text) filter (where links.status = 'active'),
          min(links.client_id::text)
        )::uuid as client_id,
        count(*) filter (where links.status = 'active') as active_location_count
      from public.academy_user_locations as links
      where links.user_id = portal_users.user_id
        and links.organization_id = owner_organization_id
    ) as linked_client on true
    left join public.clients
      on clients.id = linked_client.client_id
      and clients.organization_id = owner_organization_id
    left join public.academy_portal_access as commercial
      on commercial.organization_id = owner_organization_id
      and commercial.client_id = linked_client.client_id
    where portal_users.organization_id = owner_organization_id
      or (portal_users.organization_id is null and portal_users.status = 'pending')
  )
  select
    visible_users.user_id,
    visible_users.full_name,
    visible_users.email,
    visible_users.email_confirmed,
    visible_users.auth_disabled,
    visible_users.portal_status,
    visible_users.organization_id,
    visible_users.client_id,
    visible_users.client_name,
    visible_users.active_location_count,
    visible_users.commercial_status,
    visible_users.created_at,
    visible_users.updated_at,
    count(*) over() as total_count
  from visible_users
  where (
      normalized_search = ''
      or lower(coalesce(visible_users.full_name, '')) like '%' || normalized_search || '%'
      or lower(visible_users.email) like '%' || normalized_search || '%'
    )
    and (normalized_status is null or visible_users.portal_status = normalized_status)
    and (filter_client_id is null or visible_users.client_id = filter_client_id)
  order by
    case visible_users.portal_status when 'pending' then 0 when 'suspended' then 1 else 2 end,
    visible_users.created_at desc,
    visible_users.user_id
  limit safe_page_size
  offset safe_page_offset;
end;
$$;

create or replace function public.list_academy_portal_admin_locations()
returns table (
  client_id uuid,
  client_name text,
  client_location_id uuid,
  client_location_name text,
  city text
)
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  owner_organization_id uuid := public.current_academy_admin_organization_id();
begin
  return query
  select
    clients.id,
    clients.name,
    locations.id,
    locations.name,
    locations.city
  from public.clients
  join public.client_locations as locations
    on locations.client_id = clients.id
    and locations.organization_id = clients.organization_id
    and locations.deleted_at is null
  where clients.organization_id = owner_organization_id
    and clients.deleted_at is null
  order by clients.name, locations.name, locations.id;
end;
$$;

create or replace function public.get_academy_portal_admin_user(target_user_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  owner_organization_id uuid := public.current_academy_admin_organization_id();
  result jsonb;
begin
  select jsonb_build_object(
    'userId', portal_users.user_id,
    'fullName', profiles.full_name,
    'email', auth_users.email,
    'emailConfirmed', auth_users.email_confirmed_at is not null,
    'authDisabled', auth_users.banned_until is not null and auth_users.banned_until > now(),
    'status', portal_users.status,
    'organizationId', portal_users.organization_id,
    'createdAt', portal_users.created_at,
    'updatedAt', portal_users.updated_at,
    'statusChangedAt', portal_users.status_changed_at,
    'statusChangeReason', portal_users.status_change_reason,
    'client', case when clients.id is null then null else jsonb_build_object(
      'id', clients.id,
      'name', clients.name,
      'archived', clients.deleted_at is not null
    ) end,
    'commercial', case when commercial.client_id is null then null else jsonb_build_object(
      'status', commercial.status,
      'updatedAt', commercial.updated_at,
      'reason', commercial.status_change_reason,
      'affectedUsers', (
        select count(distinct affected.user_id)
        from public.academy_user_locations as affected
        join public.academy_portal_users as affected_users
          on affected_users.user_id = affected.user_id
          and affected_users.organization_id = affected.organization_id
        where affected.organization_id = owner_organization_id
          and affected.client_id = commercial.client_id
          and affected.status = 'active'
          and affected_users.status = 'active'
      )
    ) end,
    'locations', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', links.client_location_id,
        'clientId', links.client_id,
        'name', locations.name,
        'city', locations.city,
        'status', links.status,
        'archived', locations.deleted_at is not null,
        'grantedAt', links.granted_at,
        'grantedByName', grant_profiles.full_name,
        'revokedAt', links.revoked_at,
        'revokedByName', revoke_profiles.full_name,
        'revocationReason', links.revocation_reason
      ) order by case links.status when 'active' then 0 else 1 end, locations.name, links.client_location_id)
      from public.academy_user_locations as links
      join public.client_locations as locations
        on locations.id = links.client_location_id
        and locations.client_id = links.client_id
        and locations.organization_id = links.organization_id
      left join public.profiles as grant_profiles on grant_profiles.id = links.granted_by
      left join public.profiles as revoke_profiles on revoke_profiles.id = links.revoked_by
      where links.organization_id = owner_organization_id
        and links.user_id = portal_users.user_id
    ), '[]'::jsonb),
    'auditEvents', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', events.id,
        'action', events.action,
        'previousState', events.previous_state,
        'nextState', events.next_state,
        'reason', events.reason,
        'performedByName', actor_profiles.full_name,
        'createdAt', events.created_at,
        'clientLocationId', events.client_location_id
      ) order by events.created_at desc, events.id desc)
      from (
        select *
        from public.academy_portal_audit_events
        where organization_id = owner_organization_id
          and user_id = portal_users.user_id
        order by created_at desc, id desc
        limit 100
      ) as events
      left join public.profiles as actor_profiles on actor_profiles.id = events.performed_by
    ), '[]'::jsonb)
  )
  into result
  from public.academy_portal_users as portal_users
  join auth.users as auth_users on auth_users.id = portal_users.user_id
  left join public.profiles on profiles.id = portal_users.user_id
  left join lateral (
    select links.client_id
    from public.academy_user_locations as links
    where links.organization_id = owner_organization_id
      and links.user_id = portal_users.user_id
    order by case links.status when 'active' then 0 else 1 end, links.updated_at desc
    limit 1
  ) as linked_client on true
  left join public.clients
    on clients.id = linked_client.client_id
    and clients.organization_id = owner_organization_id
  left join public.academy_portal_access as commercial
    on commercial.organization_id = owner_organization_id
    and commercial.client_id = linked_client.client_id
  where portal_users.user_id = target_user_id
    and (
      portal_users.organization_id = owner_organization_id
      or (portal_users.organization_id is null and portal_users.status = 'pending')
    );

  if result is null then
    raise exception using errcode = 'P0002', message = 'Usuário do Portal não encontrado para esta organização.';
  end if;
  return result;
end;
$$;

create or replace function public.configure_academy_portal_user(
  target_user_id uuid,
  target_client_id uuid,
  target_location_ids uuid[],
  target_commercial_status text,
  change_reason text,
  target_expected_updated_at timestamptz default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor_id uuid := auth.uid();
  owner_organization_id uuid := public.current_academy_admin_organization_id();
  normalized_reason text := btrim(coalesce(change_reason, ''));
  normalized_locations uuid[];
  portal_record record;
  commercial_record record;
  commercial_exists boolean;
  link_record record;
  final_user_status text;
  valid_location_count integer;
begin
  if char_length(normalized_reason) < 3 or char_length(normalized_reason) > 500 then
    raise exception using errcode = '22023', message = 'Informe um motivo entre 3 e 500 caracteres.';
  end if;
  if target_commercial_status not in ('pending', 'trialing', 'active') then
    raise exception using errcode = '22023', message = 'A configuração inicial aceita somente pending, trialing ou active.';
  end if;
  if target_location_ids is null or cardinality(target_location_ids) = 0 then
    raise exception using errcode = '22023', message = 'Selecione ao menos uma unidade válida.';
  end if;
  if array_position(target_location_ids, null) is not null then
    raise exception using errcode = '22023', message = 'A lista de unidades contém um identificador inválido.';
  end if;
  select array_agg(distinct location_id order by location_id)
  into normalized_locations
  from unnest(target_location_ids) as location_id;
  if cardinality(normalized_locations) <> cardinality(target_location_ids) then
    raise exception using errcode = '23505', message = 'A mesma unidade não pode ser informada mais de uma vez.';
  end if;

  select * into portal_record
  from public.academy_portal_users
  where user_id = target_user_id
  for update;
  if not found then raise exception using errcode = 'P0002', message = 'Usuário externo não encontrado.'; end if;
  if portal_record.organization_id is not null and portal_record.organization_id <> owner_organization_id then
    raise exception using errcode = '42501', message = 'Usuário externo pertence a outra organização.';
  end if;
  if portal_record.status <> 'pending' then
    raise exception using errcode = '55000', message = 'Somente usuários aguardando liberação aceitam configuração inicial.';
  end if;
  if target_expected_updated_at is not null and portal_record.updated_at <> target_expected_updated_at then
    raise exception using errcode = 'PT409', message = 'Este usuário foi alterado por outro owner. Recarregue antes de confirmar.';
  end if;

  perform 1
  from public.clients
  where id = target_client_id
    and organization_id = owner_organization_id
    and deleted_at is null
  for update;
  if not found then raise exception using errcode = '23503', message = 'A academia não foi encontrada ou está arquivada.'; end if;

  perform 1
  from public.client_locations
  where organization_id = owner_organization_id
    and client_id = target_client_id
    and id = any(normalized_locations)
  order by id
  for update;

  select count(*) into valid_location_count
  from public.client_locations
  where organization_id = owner_organization_id
    and client_id = target_client_id
    and id = any(normalized_locations)
    and deleted_at is null;
  if valid_location_count <> cardinality(normalized_locations) then
    raise exception using errcode = '23503', message = 'Uma ou mais unidades são inválidas, arquivadas ou pertencem a outra academia.';
  end if;

  select * into commercial_record
  from public.academy_portal_access
  where organization_id = owner_organization_id
    and client_id = target_client_id
  for update;
  commercial_exists := found;

  final_user_status := case when target_commercial_status in ('trialing', 'active') then 'active' else 'pending' end;
  perform set_config('zion.academy_administration', 'allowed', true);

  update public.academy_portal_users
  set organization_id = owner_organization_id,
      status = final_user_status,
      status_changed_at = now(),
      status_changed_by = actor_id,
      status_change_reason = normalized_reason,
      updated_at = now(),
      updated_by = actor_id
  where user_id = target_user_id;

  if not commercial_exists then
    insert into public.academy_portal_access (
      organization_id, client_id, status, status_changed_at, status_changed_by,
      status_change_reason, created_by, updated_by
    ) values (
      owner_organization_id, target_client_id, target_commercial_status, now(), actor_id,
      normalized_reason, actor_id, actor_id
    );
  else
    update public.academy_portal_access
    set status = target_commercial_status,
        status_changed_at = now(),
        status_changed_by = actor_id,
        status_change_reason = normalized_reason,
        updated_at = now(),
        updated_by = actor_id
    where organization_id = owner_organization_id and client_id = target_client_id;
  end if;

  for link_record in
    select links.*
    from public.academy_user_locations as links
    where links.organization_id = owner_organization_id
      and links.user_id = target_user_id
    order by links.client_location_id
    for update
  loop
    if link_record.status = 'active' and not (link_record.client_location_id = any(normalized_locations)) then
      update public.academy_user_locations
      set status = 'revoked', revoked_at = now(), revoked_by = actor_id,
          revocation_reason = normalized_reason, updated_at = now()
      where organization_id = owner_organization_id
        and user_id = target_user_id
        and client_location_id = link_record.client_location_id;
      perform public.record_academy_portal_audit_event(
        owner_organization_id, target_user_id, link_record.client_id, link_record.client_location_id,
        'location_revoked', jsonb_build_object('status', 'active'), jsonb_build_object('status', 'revoked'),
        normalized_reason, actor_id
      );
    end if;
  end loop;

  for link_record in
    select id from public.client_locations where id = any(normalized_locations) order by id
  loop
    if exists (
      select 1 from public.academy_user_locations
      where organization_id = owner_organization_id and user_id = target_user_id
        and client_location_id = link_record.id and status = 'revoked'
    ) then
      update public.academy_user_locations
      set status = 'active', client_id = target_client_id, granted_at = now(), granted_by = actor_id,
          revoked_at = null, revoked_by = null, revocation_reason = null, updated_at = now()
      where organization_id = owner_organization_id and user_id = target_user_id
        and client_location_id = link_record.id;
      perform public.record_academy_portal_audit_event(
        owner_organization_id, target_user_id, target_client_id, link_record.id,
        'location_reactivated', jsonb_build_object('status', 'revoked'), jsonb_build_object('status', 'active'),
        normalized_reason, actor_id
      );
    elsif not exists (
      select 1 from public.academy_user_locations
      where organization_id = owner_organization_id and user_id = target_user_id
        and client_location_id = link_record.id
    ) then
      insert into public.academy_user_locations (
        organization_id, user_id, client_id, client_location_id, status, granted_at, granted_by
      ) values (
        owner_organization_id, target_user_id, target_client_id, link_record.id, 'active', now(), actor_id
      );
      perform public.record_academy_portal_audit_event(
        owner_organization_id, target_user_id, target_client_id, link_record.id,
        'location_granted', '{}'::jsonb, jsonb_build_object('status', 'active'), normalized_reason, actor_id
      );
    end if;
  end loop;

  perform public.record_academy_portal_audit_event(
    owner_organization_id, target_user_id, target_client_id, null,
    'commercial_access_changed',
    jsonb_build_object('status', coalesce(commercial_record.status, 'not_configured')),
    jsonb_build_object('status', target_commercial_status), normalized_reason, actor_id
  );
  if final_user_status = 'active' then
    perform public.record_academy_portal_audit_event(
      owner_organization_id, target_user_id, target_client_id, null,
      'user_activated', jsonb_build_object('status', portal_record.status),
      jsonb_build_object('status', 'active'), normalized_reason, actor_id
    );
  end if;
  perform public.record_academy_portal_audit_event(
    owner_organization_id, target_user_id, target_client_id, null,
    'initial_configuration_completed',
    jsonb_build_object('status', portal_record.status, 'organizationAssigned', portal_record.organization_id is not null),
    jsonb_build_object('status', final_user_status, 'commercialStatus', target_commercial_status,
      'activeLocationCount', cardinality(normalized_locations)), normalized_reason, actor_id
  );
  perform set_config('zion.academy_administration', '', true);
end;
$$;

create or replace function public.change_academy_portal_user_status(
  target_user_id uuid,
  target_status text,
  change_reason text,
  target_expected_updated_at timestamptz default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor_id uuid := auth.uid();
  owner_organization_id uuid := public.current_academy_admin_organization_id();
  normalized_reason text := btrim(coalesce(change_reason, ''));
  portal_record record;
  audit_action text;
begin
  if target_status not in ('active', 'suspended') then
    raise exception using errcode = '22023', message = 'A ação aceita somente ativação ou suspensão.';
  end if;
  if char_length(normalized_reason) < 3 or char_length(normalized_reason) > 500 then
    raise exception using errcode = '22023', message = 'Informe um motivo entre 3 e 500 caracteres.';
  end if;

  select * into portal_record
  from public.academy_portal_users
  where user_id = target_user_id
  for update;
  if not found or portal_record.organization_id <> owner_organization_id then
    raise exception using errcode = 'P0002', message = 'Usuário do Portal não encontrado para esta organização.';
  end if;
  if target_expected_updated_at is not null and portal_record.updated_at <> target_expected_updated_at then
    raise exception using errcode = 'PT409', message = 'Este usuário foi alterado por outro owner. Recarregue antes de confirmar.';
  end if;
  if portal_record.status = target_status then
    raise exception using errcode = '55000', message = 'O usuário já está neste status.';
  end if;
  if target_status = 'active' and not exists (
    select 1
    from public.academy_user_locations as links
    join public.clients
      on clients.id = links.client_id and clients.organization_id = links.organization_id
      and clients.deleted_at is null
    join public.client_locations as locations
      on locations.id = links.client_location_id and locations.client_id = links.client_id
      and locations.organization_id = links.organization_id and locations.deleted_at is null
    where links.organization_id = owner_organization_id
      and links.user_id = target_user_id
      and links.status = 'active'
  ) then
    raise exception using errcode = '55000', message = 'Adicione ao menos uma unidade válida antes de reativar o usuário.';
  end if;

  audit_action := case
    when target_status = 'suspended' then 'user_suspended'
    when portal_record.status = 'suspended' then 'user_reactivated'
    else 'user_activated'
  end;
  perform set_config('zion.academy_administration', 'allowed', true);
  update public.academy_portal_users
  set status = target_status,
      status_changed_at = now(), status_changed_by = actor_id,
      status_change_reason = normalized_reason,
      updated_at = now(), updated_by = actor_id
  where user_id = target_user_id;
  perform public.record_academy_portal_audit_event(
    owner_organization_id, target_user_id, null, null, audit_action,
    jsonb_build_object('status', portal_record.status), jsonb_build_object('status', target_status),
    normalized_reason, actor_id
  );
  perform set_config('zion.academy_administration', '', true);
end;
$$;

create or replace function public.replace_academy_portal_user_locations(
  target_user_id uuid,
  target_client_id uuid,
  target_location_ids uuid[],
  change_reason text,
  target_expected_updated_at timestamptz default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor_id uuid := auth.uid();
  owner_organization_id uuid := public.current_academy_admin_organization_id();
  normalized_reason text := btrim(coalesce(change_reason, ''));
  normalized_locations uuid[] := '{}'::uuid[];
  portal_record record;
  link_record record;
  valid_location_count integer := 0;
  remaining_count integer;
begin
  if char_length(normalized_reason) < 3 or char_length(normalized_reason) > 500 then
    raise exception using errcode = '22023', message = 'Informe um motivo entre 3 e 500 caracteres.';
  end if;
  if target_location_ids is not null and array_position(target_location_ids, null) is not null then
    raise exception using errcode = '22023', message = 'A lista de unidades contém um identificador inválido.';
  end if;
  if coalesce(cardinality(target_location_ids), 0) > 0 then
    select array_agg(distinct location_id order by location_id)
    into normalized_locations
    from unnest(target_location_ids) as location_id;
    if cardinality(normalized_locations) <> cardinality(target_location_ids) then
      raise exception using errcode = '23505', message = 'A mesma unidade não pode ser informada mais de uma vez.';
    end if;
  end if;

  select * into portal_record
  from public.academy_portal_users
  where user_id = target_user_id
  for update;
  if not found or portal_record.organization_id <> owner_organization_id then
    raise exception using errcode = 'P0002', message = 'Usuário do Portal não encontrado para esta organização.';
  end if;
  if target_expected_updated_at is not null and portal_record.updated_at <> target_expected_updated_at then
    raise exception using errcode = 'PT409', message = 'Este usuário foi alterado por outro owner. Recarregue antes de confirmar.';
  end if;

  perform 1 from public.clients
  where id = target_client_id and organization_id = owner_organization_id
    and (deleted_at is null or cardinality(normalized_locations) = 0)
  for update;
  if not found then raise exception using errcode = '23503', message = 'A academia não foi encontrada ou está arquivada.'; end if;

  if cardinality(normalized_locations) > 0 then
    perform 1 from public.client_locations
    where organization_id = owner_organization_id and client_id = target_client_id
      and id = any(normalized_locations)
    order by id for update;
    select count(*) into valid_location_count
    from public.client_locations
    where organization_id = owner_organization_id and client_id = target_client_id
      and id = any(normalized_locations) and deleted_at is null;
    if valid_location_count <> cardinality(normalized_locations) then
      raise exception using errcode = '23503', message = 'Uma ou mais unidades são inválidas, arquivadas ou pertencem a outra academia.';
    end if;
  end if;

  if exists (
    select 1 from public.academy_user_locations
    where organization_id = owner_organization_id and user_id = target_user_id
      and status = 'active' and client_id <> target_client_id
  ) then
    raise exception using errcode = '23514', message = 'Todas as unidades ativas devem pertencer à mesma academia.';
  end if;

  perform 1 from public.academy_user_locations
  where organization_id = owner_organization_id and user_id = target_user_id
  order by client_location_id for update;

  perform set_config('zion.academy_administration', 'allowed', true);
  for link_record in
    select * from public.academy_user_locations
    where organization_id = owner_organization_id and user_id = target_user_id
    order by client_location_id
  loop
    if link_record.status = 'active' and not (link_record.client_location_id = any(normalized_locations)) then
      update public.academy_user_locations
      set status = 'revoked', revoked_at = now(), revoked_by = actor_id,
          revocation_reason = normalized_reason, updated_at = now()
      where organization_id = owner_organization_id and user_id = target_user_id
        and client_location_id = link_record.client_location_id;
      perform public.record_academy_portal_audit_event(
        owner_organization_id, target_user_id, link_record.client_id, link_record.client_location_id,
        'location_revoked', jsonb_build_object('status', 'active'), jsonb_build_object('status', 'revoked'),
        normalized_reason, actor_id
      );
    end if;
  end loop;

  for link_record in
    select id from public.client_locations where id = any(normalized_locations) order by id
  loop
    if exists (
      select 1 from public.academy_user_locations
      where organization_id = owner_organization_id and user_id = target_user_id
        and client_location_id = link_record.id and status = 'revoked'
    ) then
      update public.academy_user_locations
      set status = 'active', granted_at = now(), granted_by = actor_id,
          revoked_at = null, revoked_by = null, revocation_reason = null, updated_at = now()
      where organization_id = owner_organization_id and user_id = target_user_id
        and client_location_id = link_record.id;
      perform public.record_academy_portal_audit_event(
        owner_organization_id, target_user_id, target_client_id, link_record.id,
        'location_reactivated', jsonb_build_object('status', 'revoked'), jsonb_build_object('status', 'active'),
        normalized_reason, actor_id
      );
    elsif not exists (
      select 1 from public.academy_user_locations
      where organization_id = owner_organization_id and user_id = target_user_id
        and client_location_id = link_record.id
    ) then
      insert into public.academy_user_locations (
        organization_id, user_id, client_id, client_location_id, status, granted_at, granted_by
      ) values (
        owner_organization_id, target_user_id, target_client_id, link_record.id, 'active', now(), actor_id
      );
      perform public.record_academy_portal_audit_event(
        owner_organization_id, target_user_id, target_client_id, link_record.id,
        'location_granted', '{}'::jsonb, jsonb_build_object('status', 'active'), normalized_reason, actor_id
      );
    end if;
  end loop;

  select count(*) into remaining_count
  from public.academy_user_locations
  where organization_id = owner_organization_id and user_id = target_user_id and status = 'active';
  if remaining_count = 0 and portal_record.status = 'active' then
    update public.academy_portal_users
    set status = 'pending', status_changed_at = now(), status_changed_by = actor_id,
        status_change_reason = normalized_reason, updated_at = now(), updated_by = actor_id
    where user_id = target_user_id;
    perform public.record_academy_portal_audit_event(
      owner_organization_id, target_user_id, target_client_id, null,
      'user_downgraded_no_locations', jsonb_build_object('status', 'active'),
      jsonb_build_object('status', 'pending'), normalized_reason, actor_id
    );
  else
    update public.academy_portal_users
    set updated_at = now(), updated_by = actor_id
    where user_id = target_user_id;
  end if;
  perform set_config('zion.academy_administration', '', true);
end;
$$;

create or replace function public.change_academy_portal_commercial_access(
  target_client_id uuid,
  target_status text,
  change_reason text,
  target_expected_updated_at timestamptz default null
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor_id uuid := auth.uid();
  owner_organization_id uuid := public.current_academy_admin_organization_id();
  normalized_reason text := btrim(coalesce(change_reason, ''));
  commercial_record record;
  affected_users bigint;
begin
  if target_status not in ('pending', 'trialing', 'active', 'past_due', 'suspended', 'cancelled') then
    raise exception using errcode = '22023', message = 'Situação comercial inválida.';
  end if;
  if char_length(normalized_reason) < 3 or char_length(normalized_reason) > 500 then
    raise exception using errcode = '22023', message = 'Informe um motivo entre 3 e 500 caracteres.';
  end if;
  perform 1 from public.clients
  where id = target_client_id and organization_id = owner_organization_id
    and (deleted_at is null or target_status not in ('trialing', 'active'))
  for update;
  if not found then raise exception using errcode = '23503', message = 'A academia não foi encontrada ou está arquivada.'; end if;

  select * into commercial_record
  from public.academy_portal_access
  where organization_id = owner_organization_id and client_id = target_client_id
  for update;
  if not found then raise exception using errcode = 'P0002', message = 'A situação comercial ainda não foi configurada para esta academia.'; end if;
  if target_expected_updated_at is not null and commercial_record.updated_at <> target_expected_updated_at then
    raise exception using errcode = 'PT409', message = 'A situação comercial foi alterada por outro owner. Recarregue antes de confirmar.';
  end if;
  if commercial_record.status = target_status then
    raise exception using errcode = '55000', message = 'A academia já está nesta situação comercial.';
  end if;

  select count(distinct links.user_id) into affected_users
  from public.academy_user_locations as links
  join public.academy_portal_users as portal_users
    on portal_users.user_id = links.user_id and portal_users.organization_id = links.organization_id
  where links.organization_id = owner_organization_id and links.client_id = target_client_id
    and links.status = 'active' and portal_users.status = 'active';

  perform set_config('zion.academy_administration', 'allowed', true);
  update public.academy_portal_access
  set status = target_status, status_changed_at = now(), status_changed_by = actor_id,
      status_change_reason = normalized_reason, updated_at = now(), updated_by = actor_id
  where organization_id = owner_organization_id and client_id = target_client_id;
  perform public.record_academy_portal_audit_event(
    owner_organization_id, null, target_client_id, null, 'commercial_access_changed',
    jsonb_build_object('status', commercial_record.status, 'affectedUsers', affected_users),
    jsonb_build_object('status', target_status, 'affectedUsers', affected_users), normalized_reason, actor_id
  );
  perform set_config('zion.academy_administration', '', true);
  return affected_users;
end;
$$;

revoke all on function public.guard_academy_portal_audit_event() from public, anon, authenticated;
revoke all on function public.current_academy_admin_organization_id() from public, anon, authenticated;
revoke all on function public.record_academy_portal_audit_event(uuid, uuid, uuid, uuid, text, jsonb, jsonb, text, uuid) from public, anon, authenticated;
revoke all on function public.get_academy_portal_admin_summary() from public, anon;
revoke all on function public.list_academy_portal_admin_users(text, text, uuid, integer, integer) from public, anon;
revoke all on function public.list_academy_portal_admin_locations() from public, anon;
revoke all on function public.get_academy_portal_admin_user(uuid) from public, anon;
revoke all on function public.configure_academy_portal_user(uuid, uuid, uuid[], text, text, timestamptz) from public, anon;
revoke all on function public.change_academy_portal_user_status(uuid, text, text, timestamptz) from public, anon;
revoke all on function public.replace_academy_portal_user_locations(uuid, uuid, uuid[], text, timestamptz) from public, anon;
revoke all on function public.change_academy_portal_commercial_access(uuid, text, text, timestamptz) from public, anon;

-- A Etapa 11 concentra toda mutação administrativa nas RPCs auditadas acima.
-- As RPCs legadas da fundação continuam no catálogo para compatibilidade de
-- schema, mas deixam de ser superfícies chamáveis pelo navegador.
revoke execute on function public.set_academy_portal_user_status(uuid, uuid, text, text) from authenticated;
revoke execute on function public.set_academy_portal_access(uuid, uuid, text, text) from authenticated;
revoke execute on function public.grant_academy_location_access(uuid, uuid, uuid, uuid) from authenticated;
revoke execute on function public.revoke_academy_location_access(uuid, uuid, uuid, text) from authenticated;

grant execute on function public.get_academy_portal_admin_summary() to authenticated;
grant execute on function public.list_academy_portal_admin_users(text, text, uuid, integer, integer) to authenticated;
grant execute on function public.list_academy_portal_admin_locations() to authenticated;
grant execute on function public.get_academy_portal_admin_user(uuid) to authenticated;
grant execute on function public.configure_academy_portal_user(uuid, uuid, uuid[], text, text, timestamptz) to authenticated;
grant execute on function public.change_academy_portal_user_status(uuid, text, text, timestamptz) to authenticated;
grant execute on function public.replace_academy_portal_user_locations(uuid, uuid, uuid[], text, timestamptz) to authenticated;
grant execute on function public.change_academy_portal_commercial_access(uuid, text, text, timestamptz) to authenticated;

comment on table public.academy_portal_audit_events is
  'Histórico append-only das ações administrativas do Portal da Academia, sem payloads sensíveis.';
comment on function public.list_academy_portal_admin_users(text, text, uuid, integer, integer) is
  'Lista somente usuários vinculados à organização do owner e cadastros ainda não atribuídos da fila segura de onboarding.';
comment on function public.replace_academy_portal_user_locations(uuid, uuid, uuid[], text, timestamptz) is
  'Substitui atomicamente as unidades permitidas. Ao revogar a última unidade, rebaixa usuário ativo para pending.';

commit;
